### ISSUE TITLE
License

### ISSUE THREAD

**Issue by walczak-patryk** [dboures/Hive#1]
Hi,
I am currently writing my diploma thesis on artificial intelligence in hex, othello and hive games. Your game implementation is the best/most suitable for my thesis that I found. There is no description of the license You provided, could You possibly add that part? Otherwise, could I model my work after yours, or use parts of it?

**Comment by dboures** [comment]
Hey I just added an MIT License. Feel free to use the code however you like! I wrote this just for fun a few months ago, so not sure how useful/correct it is.
